name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 3.1.4

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  firebase_core:
    git:
      url: https://github.com/komi1230/flutterfire
      ref: patch/streets
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/komi1230/flutterfire
      ref: patch/streets
      path: packages/firebase_core/firebase_core_web
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/komi1230/flutterfire
      ref: patch/streets
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
